<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Totally real app</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <h1>Response from Function</h1>
    <button onclick="callWithRetry(callFunction2).catch(console.error)">Say goodbye</button>
    <button onclick="callWithRetry(callFunction1).catch(console.error)">Say hello</button>
    <div id="main">Loading...</div>
    <script>
        async function callFunction1() {
            const response = await fetch("http://localhost:7071/api/hello");
            document.getElementById("main").innerHTML = `<pre>${await response.text()}</pre>`;
        }

        async function callFunction2() {
            const response = await fetch("http://localhost:7071/api/goodbye");
            document.getElementById("main").innerHTML = `<pre>${await response.text()}</pre>`;
        }

        async function callWithRetry(fn) {
            let retry = 5;
            while(retry--) {
                try {
                    return await fn();
                } catch (err) {
                    console.warn(err);
                    console.warn("Caught error in retry. Trying again in 1 second");
                    await sleep(1000);
                }
            }
            throw new Error("Hit max retry count.")
        }

        async function sleep(number) {
            return new Promise((res) => {
                setTimeout(() => {
                    res();
                }, number);
            });
        }

        callFunction1().catch(console.error);
    </script>
</body>
</html>